### PR TITLE
French translation added

### PR DESCRIPTION
**Pull request by Anne017**
Thanks for your amazing work!
Here is a proposal of translation in French.
Have you ever considered to host the translations in [Launchpad](https://wiki.ubuntu.com/Translations/LpProjectConfiguration), this way the translations could be more easily reviewed by Ubuntu Translators?

### CODE REVIEW

**Comment by bhdouglass** [comment]
Thank you for the translation! I have considered putting it on Launchpad, I've unfortunately haven't gotten the scope template I used to pull all the translatable strings (and unfortunately anyone I've asked hasn't been able to help). I'll probably just have to forget the template and work up my own solution as having translations is important to me.

**Comment by bhdouglass** [comment]
I just setup translations on launchpad, there are a few more strings to translate now. - https://translations.launchpad.net/owncloud-files-scope

**Comment by Anne017** [comment]
Thanks a lot!
I have translated the new strings in French.

**Comment by bhdouglass** [comment]
Thank you! I'll be doing a release with the new translations soon.

**Pull request merged**
